---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: instrumentation
  labels:
    app: elasticsearch
    elasticsearch-node-type: data
spec:
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: RollingUpdate
  serviceName: elasticsearch-data
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
        elasticsearch-node-type: data
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - elasticsearch
                  - key: "elasticsearch-node-type"
                    operator: In
                    values:
                      - data
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - elasticsearch
                    - key: "elasticsearch-node-type"
                      operator: In
                      values:
                        - data
                topologyKey: failure-domain.beta.kubernetes.io/zone
      securityContext:
        fsGroup: 1000
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
          name: data
          command:
            - "/bin/bash"
            - "/tmp/bin/start-elasticsearch.sh"
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 1
              memory: 4Gi
          ports:
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
            - name: startup
              mountPath: /tmp/bin
          env:
            - name: "ES_JAVA_OPTS"
              value: "-Xms2g -Xmx2g"
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ES_CLUSTER_NAME
              value: instrumentation-cluster
            - name: ES_MASTER_SERVICE_NAME
              value: elasticsearch-master
            - name: ES_IS_DATA
              value: "1"
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "set -eo pipefail && curl -fs localhost:9200/_cat/health?h=st | grep 'green'"
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 2
      volumes:
        - name: startup
          configMap:
            name: elasticsearch-startup-1
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-init
        securityContext:
          privileged: true
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
