---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-v2.0.4
  namespace: instrumentation
  labels:
    k8s-app: fluentd
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    version: v2.0.4
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd
        kubernetes.io/cluster-service: "true"
        version: v2.0.4
    spec:
      serviceAccountName: fluentd
      containers:
        - name: fluentd
          image: gcr.io/google_containers/fluentd-elasticsearch:v2.0.4
          command:
            - '/bin/sh'
            - '-c'
            - '/run.sh $FLUENTD_ARGS'
          env:
            - name: FLUENTD_ARGS
              value: -q
            - name: FLUENTD_ELASTICSEARCH_HOST
              value: "elasticsearch"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config-volume
              mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config-volume
          configMap:
            name: fluentd-es-config
